# this docker-compose file supports to build (not support to run services)

version: '2'

services:
  vm:
    build: sshd-container
    image: hana/sshd-container

  vm-unbound:
    build: unbound-container
    image: hana/unbound-container

  vm-hanad:
    build: hanad-container
    image: hana/hanad-container

  vm-hanapeerd:
    build: hanapeerd-container
    image: hana/hanapeerd-container

  vm-hanaroute:
    build: hanaroute-container
    image: hana/hanaroute-container

  vm-hanansupdate:
    build: hanansupdate-container
    image: hana/hanansupdate-container

  vm0-dns-serevr:
    build: dns-server-container
    image: hana/dns-server-container

  vm0-hanavis-server:
    build: hanavis-server-container
    image: hana/hanavis-server-container

  vm0-hanavis-mysql:
    build: hanavis-mysql-container
    image: hana/hanavis-mysql-container

  vm0-hanavis-httpd:
    build: hanavis-httpd-container
    image: hana/hanavis-httpd-container

